# Generated by Django 6.0.7 on 2026-09-03 23:35

import content.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="releaseYear",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1888, message="Release year can't be before 1888."
                    ),
                    django.core.validators.MaxValueValidator(
                        content.models.current_year_plus_one,
                        message="Release year can't be more than one year in the future.",
                    ),
                ]
            ),
        ),
    ]
